---
# tasks file for hswong3i.mount

- name: mount the source
  mount:
    src: "{{ item.src }}"
    name: "{{ item.name }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: "{{ item.state }}"
  with_items: "{{ mount }}"
  tags: hswong3i.mount
