---
# tasks file for hswong3i.mount

- name: prepare target mount directory
  file:
    dest: "{{ item.name }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ 'directory' if item.state != 'absent' else 'absent' }}"
  with_items: "{{ mount }}"
  tags: hswong3i.mount

- name: mount the source
  mount:
    src: "{{ item.src }}"
    name: "{{ item.name }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: "{{ item.state }}"
  with_items: "{{ mount }}"
  tags: hswong3i.mount
