---
# tasks file for hswong3i.mount

- name: include release specific variables
  include_vars: "{{ ansible_distribution_release }}.yml"
  tags: hswong3i.mount

- name: apt-add-repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt_repository }}"
  tags: hswong3i.mount

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt }}"
  tags: hswong3i.mount

- name: mount the source
  mount:
    src: "{{ item.src }}"
    name: "{{ item.name }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    dump: "{{ item.dump }}"
    passno: "{{ item.passno }}"
    state: "{{ item.state }}"
  with_items: "{{ mount }}"
  tags: hswong3i.mount
